require('dotenv').config();
const {REST,Routes,SlashCommandBuilder}=require('discord.js');
const countryChoices=[{name:'🇹🇷 Türkiye',value:'turkiye'},{name:'🇩🇪 Almanya',value:'almanya'},{name:'🇫🇷 Fransa',value:'fransa'},{name:'🇪🇸 İspanya',value:'ispanya'}];
const commands=[
new SlashCommandBuilder().setName('verify').setDescription('Roblox hesabını Discord hesabına bağlar.'),
new SlashCommandBuilder().setName('update').setDescription('Roblox rütbeni Discord ile senkronize eder.'),
new SlashCommandBuilder().setName('grup-istek').setDescription('Bekleyen Roblox grup katılım isteğini kabul eder.').addStringOption(o=>o.setName('kullanici').setDescription('Roblox kullanıcı adı').setRequired(true)).addStringOption(o=>o.setName('ulke').setDescription('Ülke grubu').setRequired(true).addChoices(...countryChoices)).addStringOption(o=>o.setName('sebep').setDescription('İşlem sebebi').setRequired(true)),
new SlashCommandBuilder().setName('grup-at').setDescription('Roblox kullanıcısını gruptan çıkarır.').addStringOption(o=>o.setName('kullanici').setDescription('Roblox kullanıcı adı').setRequired(true)).addStringOption(o=>o.setName('ulke').setDescription('Ülke grubu').setRequired(true).addChoices(...countryChoices)).addStringOption(o=>o.setName('sebep').setDescription('İşlem sebebi').setRequired(true)),
new SlashCommandBuilder().setName('rütbe-sorgu').setDescription('Roblox kullanıcısının ülke gruplarındaki rütbelerini gösterir.').addStringOption(o=>o.setName('kullanici').setDescription('Roblox kullanıcı adı').setRequired(true)),
new SlashCommandBuilder().setName('grup-listele').setDescription('Roblox kullanıcısının gruplarını listeler.').addStringOption(o=>o.setName('kullanici').setDescription('Roblox kullanıcı adı').setRequired(true)),
new SlashCommandBuilder().setName('rütbe-terfi').setDescription('Bir sonraki gerçek Roblox rütbesine terfi ettirir.').addStringOption(o=>o.setName('kullanici').setDescription('Roblox kullanıcı adı').setRequired(true)).addStringOption(o=>o.setName('ulke').setDescription('Ülke grubu').setRequired(true).addChoices(...countryChoices)).addStringOption(o=>o.setName('sebep').setDescription('Terfi sebebi').setRequired(true)),
new SlashCommandBuilder().setName('rütbe-degistir').setDescription('Doğrulanmış ülkeye göre Roblox rütbesini değiştirir.').addUserOption(o=>o.setName('kullanici').setDescription('Discord kullanıcısı').setRequired(true)).addStringOption(o=>o.setName('rutbe').setDescription('Gerçek Roblox rütbesi').setAutocomplete(true).setRequired(true)).addStringOption(o=>o.setName('sebep').setDescription('Rütbe değiştirme sebebi').setRequired(true)),
new SlashCommandBuilder().setName('profil').setDescription('Discord ve Roblox profil bilgilerini gösterir.'),
new SlashCommandBuilder().setName('duyuru').setDescription('Personel duyurusu oluşturur.'),
new SlashCommandBuilder().setName('ticket-panel').setDescription('Ticket paneli oluşturur.'),
new SlashCommandBuilder().setName('mute').setDescription('Kullanıcıyı susturur.').addUserOption(o=>o.setName('kullanici').setDescription('Kullanıcı').setRequired(true)).addIntegerOption(o=>o.setName('dakika').setDescription('Dakika').setMinValue(1).setMaxValue(40320).setRequired(true)).addStringOption(o=>o.setName('sebep').setDescription('Sebep').setRequired(true)),
new SlashCommandBuilder().setName('unmute').setDescription('Susturmayı kaldırır.').addUserOption(o=>o.setName('kullanici').setDescription('Kullanıcı').setRequired(true)).addStringOption(o=>o.setName('sebep').setDescription('Sebep').setRequired(true)),
new SlashCommandBuilder().setName('kick').setDescription('Kullanıcıyı atar.').addUserOption(o=>o.setName('kullanici').setDescription('Kullanıcı').setRequired(true)).addStringOption(o=>o.setName('sebep').setDescription('Sebep').setRequired(true)),
new SlashCommandBuilder().setName('ban').setDescription('Kullanıcıyı yasaklar.').addUserOption(o=>o.setName('kullanici').setDescription('Kullanıcı').setRequired(true)).addStringOption(o=>o.setName('sebep').setDescription('Sebep').setRequired(true))
].map(x=>x.toJSON());
(async()=>{try{const rest=new REST({version:'10'}).setToken(process.env.DISCORD_TOKEN);await rest.put(Routes.applicationGuildCommands(process.env.DISCORD_CLIENT_ID,process.env.DISCORD_GUILD_ID),{body:commands});console.log(`TÜM SLASH KOMUTLARI HAZIR: ${commands.length}`);}catch(e){console.error(e);process.exitCode=1;}})();
